### PR TITLE
Create new file jquery.mmenu.setmenu.js

### PR DESCRIPTION
**Pull request by anthHugo**
Set menu in function of URLs

### CODE REVIEW

**Comment by FrDH** [comment]
Could you please explain what this add-on is supposed to do?
Is it trying to find the anchor that links to the current page and set the `LI` as selected?

**Comment by anthHugo** [comment]
Hi,

This add-on must selected the menu based on the current url, so  set the LI

**Comment by FrDH** [comment]
I like the idea, but I'm not sure `setMenu` is an appropriate name. Also, why is `nbRecursion` set to 3 by default? Shouldn't the loop simply continue till the start of `url`?

**Comment by FrDH** [comment]
I've added this add-on in the latest version, named it "currentItem" though :)
http://mmenu.frebsite.nl/documentation/addons/current-item.html

**Pull request closed without merging**
