### PR TITLE
Issue #370. Menu back is broken in IE9.

### PR DESCRIPTION
**Pull request by wallybh**
Adding class mn-hidden to the currently closing panel.

### CODE REVIEW

**Comment by wallybh** [comment]
Please ignore the format changes. The atom editor did that changes automatically. The only important change is in line 151

**Comment by FrDH** [comment]
I still wonder why IE9 would break because of that. But if it works, I'll merge this pull request (including the format changes :) )

**Comment by wallybh** [comment]
Got it. I'll change my code.

**Comment by wallybh** [comment]
Hi, @FrDH!

I added a function to check if browser supports css transitions. 

I put this check in _c.supportsTransition variable to avoid multiple checks.

**Comment by FrDH** [comment]
Nice one, except that `_c` is used for storing prefixed classnames(, `_d` for data-attributes and `_e` for events). 
I'd use `$.mmenu.support`. It is intended for storing feature detection, much like the deprecated jQuery.support used to do.

To avoid multiple checks, could you also first check if Modernizr is available and if so, use their test?
````javascript
if ( Modernizr && Modernizr.csstransitions ) { return true; }
else if ( ... )
````

Thanks again

**Comment by wallybh** [comment]
Got it. Sorry about the wrong use of _c global. I'm working on it right now.

**Comment by wallybh** [comment]
Hi, @FrDH!

I moved and renamed_c.supportsTransitions to $mmenu.support.csstransition. Also, I put a test checking if Modernizr is referred and then I use his test. 

I apologize for my code. I'm not familiarized with JS.

**Comment by FrDH** [comment]
Can't automatically merge it via Git, but I'll manually implement the fix in the next version.
Thanks a lot :)

**Comment by FrDH** [comment]
I believe the issue is fixed now, thanks a lot!

**Pull request closed without merging**
